name: MinecraftAchievements
main: com.SkyIsland.MinecraftAchievements.MinecraftAchievementsPlugin
version: 1.0
permissions:
    minecraftachievements.admin:
        default: op
commands:
    report:
        description: Prints out a report of the current player manager's records
        usage: /report [filename] {overwrite}
        permission: minecraftachievements.admin
    playersnapshot:
        description: Takes a snapshot of the player database and stores it at the given location
        usage: /snapshot [filename] {overwrite}
        permission: minecraftachievements.admin
    cleardata:
        description: Clears the player database of all player records kept by the plugin.
        usage: /cleardata
        permission: minecraftachievements.admin
    activateplayer:
        description: Activates the given player and begins tracking them
        usage: /activateplayer [playername | @a]
        permission: minecraftachievements.admin
    printachievementstatus:
        description: Prints general information about the current session or a specific player
        usage: /pastatus {playername}
        permission: minecraftachievements.admin
        aliases: pastatus